

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "Tester\App.config"
//     Connection String Name: "MyDbContext"
//     Connection String:      "Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=win81)(PORT=1521)))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=XE)));User Id=efpoco;password=**zapped**;"
// ------------------------------------------------------------------------------------------------

// -----------------------------------------------------------------------------------------
// Failed to read database schema in LoadTables() - ORA-12545: Network Transport: Unable to resolve connect hostname   at OracleInternal.ConnectionPool.PoolManager`3.Get(ConnectionString csWithDiffOrNewPwd, Boolean bGetForApp, CriteriaCtx criteriaCtx, String affinityInstanceName, Boolean bForceMatch)    at OracleInternal.ConnectionPool.OraclePoolManager.Get(ConnectionString csWithNewPassword, Boolean bGetForApp, CriteriaCtx criteriaCtx, String affinityInstanceName, Boolean bForceMatch)    at OracleInternal.ConnectionPool.OracleConnectionDispenser`3.Get(ConnectionString cs, PM conPM, ConnectionString pmCS, SecureString securedPassword, SecureString securedProxyPassword, CriteriaCtx criteriaCtx)    at Oracle.ManagedDataAccess.Client.OracleConnection.Open()    at Microsoft.VisualStudio.TextTemplating8ADACEBBEFE79038170A9853939676D34968715041ACB4C54CF90EA6434D8DA23D3A5CE53BFED2D66E5CC53524301113B4DCD054C5AB51CBF0BC641E521F7330.GeneratedTextTransformation.LoadTables(DbProviderFactory factory) in C:\Users\nleong\Dropbox\work\ef.reverse.poco.generator\git\nunoleong--EntityFramework-Reverse-POCO-Code-First-Generator\Tester\..\EntityFramework.Reverse.POCO.Generator\EF.Reverse.POCO.Core.ttinclude:line 682
// -----------------------------------------------------------------------------------------

